version: "3.4"

services:
  ckan:
    restart: always
    build:
      context: .
      dockerfile: images/ckan/Dockerfile.ckan
    ports:
      - 5000:5000
    depends_on:
      - db
      - solr
      - redis
    links:
      - datapusher
      - db
      - redis
      - solr

  datapusher:
    image: clementmouchet/datapusher

  db:
    build:
      context: images/postgresql/
      args:
        - DATASTORE_READONLY_PASSWORD=${DATASTORE_READONLY_PASSWORD}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    environment:
      - DATASTORE_READONLY_PASSWORD=${DATASTORE_READONLY_PASSWORD}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/db
    restart: always
    ports:
      - "5432:5432"

  redis:
    image: redis:latest

  solr:
    image: ckan/solr
    ports:
      - "8983:8983"
