version: "3"

services:
  apache-app:
    build: .
    depends-on:
      - database
      - solr
      - datapusher
      - redis
      - ckan

  database:
    image: postgres:latest
    ports: "5432:5432"
    environment:
      POSTGRES_PASSWORD: 26487666Cal
      POSTGRES_USER: ckan
      POSTGRES_DB: ckan
    volumes:
      - ./init.sql:/postgres/docker-entrypoint-initdb.d/init.sql

  solr:
    image: solr:latest
    build: solr/
    ports:
      - "8983:8983"
    volumes:
      - ./travis-build.bash:/solr/travis-build.bash

  datapusher:
    image: keitaro/datapusher
    ports: "8800:8800"
    volumes:
      - ./init.py:/datapusher/init.py

  redis:
    image: redis:alpine

  ckan:
    image: ckan/ckan
    build:
      context: .
      dockerfile: Dockerfile
    depends-on:
      - database
      - solr
      - datapusher
      - redis
    ports:
      - "5000:5000"
    volumes:
      - .:/srv/app/src_extensions
      - ckan_storage:/var/lib/ckan
