version: "3"

services:
  ckan:
    image: ckan/ckan
    env_file:
      - .dev.env
    links:
      - db
      - solr
      - redis
      - datapusher
    ports:
      - "0.0.0.0:5000:5000"
    volumes:
      - ./ckanext:/srv/app/src_extensions
      - ckan_storage:/var/lib/ckan

  datapusher:
    container_name: datapusher
    build:
      context: datapusher/
    ports:
      - "8800:8800"

  db:
    container_name: db
    env_file:
      - .dev.env
    image: postgres:12
    environment:
      PGDATA: /var/lib/postgresql/data/access_data/
    restart: always
    build:
      context: postgresql/
    volumes:
      - pg_data:/var/lib/postgresql/data

  solr:
    container_name: solr
    image: ckan/solr
    ports:
      - "8983:8983"

  redis:
    container_name: redis
    image: redis:alpine

volumes:
  ckan_storage:
  pg_data:
