version: "3"

services:
  nginx:
    build:
      context: nginx/
      dockerfile: Dockerfile
    depends_on:
      - ckan
    ports:
      - "0.0.0.0:443:443"

  database:
    image: postgres:12
    build: postgres/
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  solr:
    image: ckan/solr
    ports:
      - "0.0.0.0:8983:8983"
    volumes:
      - ./travis-build.bash:/solr/travis-build.bash

  datapusher:
    image: clementmouchet/datapusher

  redis:
    image: redis:alpine

  ckan:
    build:
      context: ckan/
      dockerfile: Dockerfile
      args:
        - TZ=${TZ}
    env_file:
      - .env
    depends_on:
      - database
      - solr
      - redis
    ports:
      - "0.0.0.0:${CKAN_PORT}:5000"

volumes:
  ckan_config:
  ckan_home:
  ckan_storage:
  pg_data:
  solr_data:
