version: "3.4"

volumes:
  pg_data:

services:
  ckan:
    env_file:
      - .env
    volumes:
      - ./:/srv/app/src_extensions

  datapusher:
    restart: always

  solr:
    restart: always

  db:
    build:
      args:
        - DATASTORE_READONLY_PASSWORD=${DATASTORE_READONLY_PASSWORD}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    environment:
      - DATASTORE_READONLY_PASSWORD=${DATASTORE_READONLY_PASSWORD}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/db
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    restart: always
